<?php
$product = $block->getProductDetails();
//print_r($product);die;
?>


<table style="width:100%">
  <tr>
    <th>Product Name</th>
    <th>Product Image</th>
    <th>Product Price</th>
  <tr>
    <td><?php echo $product['productName'] ?></td>
    <td><img src="<?php echo $product['productImage'] ?>" width="100" height="100"></td>
    <td><?php echo $product['productPrice'] ?></td>
  </tr>
 
</table>



<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>



  