<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<form action="/action_page.php" method="post">
  <div class="container">
    <label for="name"><b>Name</b></label>
    <input id="name-validation" type="text" placeholder="Enter Name" name="name" required>
    <p style="color:red;">Please Enter Alphabets Charecter Only !</p>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="txtEmail" onkeyup="ValidateEmail();">
    <p id="lblError" style="color: red"></p>

    <label for="sub"><b>Subject</b></label>
    <input type="text" placeholder="Enter Subject" name="subject" required>

    <label for="desc"><b>Description</b></label>
    <textarea id="description" name="description" rows="4" cols="50" placeholder="Description"></textarea>
        
    <button type="submit">Submit</button>
   
  </div>

</form>

</body>
</html>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script>
    function nameInput(event) {
    var value = String.fromCharCode(event.which);
    var pattern = new RegExp(/[a-zåäö ]/i);
    return pattern.test(value);
    }

    $('#name-validation').bind('keypress', nameInput);

    function ValidateEmail() {
        var email = document.getElementById("txtEmail").value;
        var lblError = document.getElementById("lblError");
        lblError.innerHTML = "";
        var expr = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
        if (!expr.test(email)) {
            lblError.innerHTML = "Please Enter Valid Email Address.";
        }
    }

    $("#description").prop('maxlength', '250');


   

</script>

<style>
body {font-family: Arial, Helvetica, sans-serif;}
form {border: 3px solid #f1f1f1;}

input[type=text], input[type=password] {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;
}

button {
  background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
}

button:hover {
  opacity: 0.8;
}

.cancelbtn {
  width: auto;
  padding: 10px 18px;
  background-color: #f44336;
}

.imgcontainer {
  text-align: center;
  margin: 24px 0 12px 0;
}

img.avatar {
  width: 40%;
  border-radius: 50%;
}

.container {
  padding: 16px;
}

span.psw {
  float: right;
  padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
  span.psw {
     display: block;
     float: none;
  }
  .cancelbtn {
     width: 100%;
  }
}
</style>