<?php
$totalCurrentProductLike = $block->getCurrentProductCount(); // product like count
$productId = $block->getProductId(); // product id
$customerId = $block->getCustomerId(); // customer id
$checkLikeDislike = $block->checkLikeDislike(); // git likedislike value
$getCustomProductAttributeValue = $block->getCustomProductAttributeValue(); // get custom product attribute
?>

    <div>
        <div style="font-family:arial;font-size:20px;"><a >Product Dimention :- <span style="color:green;"><?php echo $getCustomProductAttributeValue['dimention']; ?></span></a></div>
        <div style="font-family:arial;font-size:20px;"><a >Product Color :- <span style="color:green;"><?php echo $getCustomProductAttributeValue['productColor']; ?></span></a></div>
        
    </div>
<?php
if($customerId > 0)
{
?>
    <div>
        <div style="font-family:arial;font-size:20px;"><a >Total Like :- <span style="color:red;"><?php echo $totalCurrentProductLike; ?></span></a></div>
        <div id="productId" data-product-id="<?php echo $productId; ?>"></div>
        <div id="customerId" data-customer-id="<?php echo $customerId; ?>"></div>
        <div class="button_action"><a <?php if($checkLikeDislike == 1) { ?> class="active" <?php } ?> href="javascript:;" data-val="1">Like</a></div>
        <div class="button_action"><a <?php if($checkLikeDislike == 0) { ?> class="active" <?php } ?> href="javascript:;" data-val="0">DisLike</a></div>

    </div>
<?php 
} 
?>
