<?php
$totalCurrentProductLike = $block->getCurrentProductCount(); // product like count
$productId = $block->getProductId(); // product id
 $customerId= $block->getCustomerId(); // customer id
$checkLikeDislike = $block->checkLikeDislike(); // git likedislike value
$getCustomProductAttributeValue = $block->getCustomProductAttributeValue(); // get custom product attribute
///print_r($productId);die;
?>

    <div class = "ClsDb">
        <p><a href="customeproduct/product/details?pId=<?php echo $productId ?>">Product Additional Info</a></p>
        <p ><a >Product Dimention :- <span style="color:green;"><?php echo $getCustomProductAttributeValue['dimention']; ?></span></a></p>
        <p ><a >Product Color :- <span style="color:green;"><?php echo $getCustomProductAttributeValue['productColor']; ?></span></a></p>
        <p ><a >Total Like :- <span style="color:red;"><?php echo $totalCurrentProductLike; ?></span></a></p>
        <p id="productId" data-product-id="<?php echo $productId; ?>"></p>
        <p id="customerId" data-customer-id="<?php echo $customerId; ?>"></p>
        <div class="button-container">
        <div class="button_action"><a <?php if($checkLikeDislike == 1) { ?> class="active" <?php } ?> href="javascript:;" data-val="1">Like</a></div>
        <div class="button_action"><a <?php if($checkLikeDislike == 0) { ?> class="active" <?php } ?> href="javascript:;" data-val="0">DisLike</a></div>
        </div>
    </div>

   
