<?php /** @var Thecoachsmb\Mymodule\Block\Article $block */ ?>
<?php $articleCollection = $block->getCollection(); ?>

<table style="width:100%">
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <?php if (count($articleCollection)) { ?>
  <?php foreach($articleCollection as $post): ?>
  <tr>
    <td><p><?php echo $post->getFirstname(); ?></p> </td>
    <td><p><?php echo $post->getLastname(); ?></p> </td>
    <td><p><?php echo $post->getEmail(); ?></p> </td>
    <td><p><?php echo $post->getDob(); ?></p> </td>
  </tr>
  <?php } ?>
  <?php endforeach; ?> 
</table>



  