<?php /** @var Thecoachsmb\Mymodule\Block\Article $block */ ?>
<?php $articleCollection = $block->getCollection(); 
//echo "<pre>";
//print_r($articleCollection);die;
?>

<table style="width:100%">
  <tr>
    <th>FirstName</th>
    <th>LastName</th>
    <th>Email</th>
    <th>Dob</th>
  </tr>
  <?php foreach($articleCollection as $value) { ?>
  <tr>
    <td><?php echo $value['firstname'] ?></td>
    <td><?php echo $value['lastname'] ?></td>
    <td><?php echo $value['email'] ?></td>
    <td><?php echo $value['dob'] ?></td>
  </tr>
 <?php } ?>
 
</table>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>



  