<!-- <h1>Booking page </h1>

<form action="<?php //echo $block->getFormAction() ?>" method="post">
    <input name="firstname" type="text" placeholder="First Name" required>
    <input name="lastname" type="text" placeholder="Last Name" required>
    <input name="email" type="text" placeholder="Email" required>
    <input name="dob" type="date" placeholder="dob" required>
    <input type="submit" name="Save" value="Save">
</form> -->

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<form data-mage-init='{"validation": {}}' class="form" id="custom-form" action="<?php echo $block->getFormAction() ?>" method="post">
  <div class="container">

    <label for="name"><b>First Name</b></label>
    <input  type="text" placeholder="First Name" name="firstname" data-validate="{required:true, 'validate-alpha':true}">
   
    <label for="name"><b>Last Name</b></label>
    <input  type="text" placeholder="Last Name" name="lastname" data-validate="{required:true, 'validate-alpha':true}">
   

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="email_address" data-validate="{required:true, 'validate-email':true}">
   

    <label for="sub"><b>DOB</b></label>
    <input type="date" placeholder="DOB" name="dob" data-validate="{required:true}">
 
    <button type="submit">Submit</button>
   
  </div>

</form>

</body>
</html>





