
<?php
$sessionData = $block->getSessionValue();
?>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="button_action"><a href="/review/productreview/reviewform">Back</a></div>
<form data-mage-init='{"validation": {}}' class="form" id="custom-form" action="<?php echo $block->getFormAction() ?>" method="post">
  <div class="container">

    <input type="hidden" name="product_id" value="<?php echo $sessionData['customProductID']; ?>">
    <input type="hidden" name="customer_id" value="<?php echo $sessionData['customCustomerID']; ?>">
    <label for="name"><b>Name</b></label>
    <input  type="text" placeholder="Name" name="name" data-validate="{required:true, 'validate-alpha':true}">
   
    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="email_address" data-validate="{required:true, 'validate-email':true}">
   
    <label for="name"><b>Contact Number</b></label>
    <input  type="number" placeholder="Contact Number" name="contact_no" data-validate="{required:true}">
   
    <label for="sub"><b>Product Description</b></label>
    <textarea id="product_description" name="product_description" rows="4" cols="50" placeholder="Product Description" data-validate="{required:true}"></textarea>
    
    <label for="name"><b>Product Rating</b></label>
    <select name="product_rating" data-validate="{required:true}">
    <option value="">Select Rating</option>
     <option value="1">1</option>
     <option value="2">2</option>
     <option value="3">3</option>
     <option value="4">4</option>
     <option value="5">5</option>
    </select>

    <button type="submit">Submit</button>
   
  </div>

</form>

</body>
</html>





