<?php /** @var Thecoachsmb\Mymodule\Block\Article $block */ ?>
<?php $getConfiguration = $block->getCustomStoreConfiguration(); 
//echo "<pre>";
//print_r($getConfiguration);die;
?>
<table style="width:100%">
  <tr>
    <th>First Field</th>
    <th>Second Field Select</th>
    <th>Third Field Multi Select</th>
  </tr>
  <tr>
    <td><?php echo $getConfiguration['firstTextField']; ?></td>
    <td><?php if($getConfiguration['secondSelectField'] == 0) { echo "No"; } else { echo "Yes"; } ?></td>
    <td><?php echo $getConfiguration['thirdMultiSelectField']; ?></td>
 
</table>




<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>



  